"""Stage 2: training.

Load dataset -> preprocessing (fit on train, save fitted state for inference) -> build workflow ->
``fit_offline`` with per-batch augmentations -> save approximator + loss curve.
"""

from __future__ import annotations

import logging
import os

import numpy as np

from hydrabflow.augmentation.registry import build_augmentations
from hydrabflow.pipeline import artifacts, io
from hydrabflow.pipeline._app import make_cli
from hydrabflow.pipeline.adapter import select_adapter_keys
from hydrabflow.pipeline.workflow import build_workflow
from hydrabflow.preprocessing.registry import build_pipeline
from hydrabflow.utils.oom import run_with_oom_backoff
from hydrabflow.utils.paths import PREPROCESSING_STATE, get_run_dir
from hydrabflow.utils.seed import seed_everything

log = logging.getLogger(__name__)


def run_training(cfg):
    """Train the approximator and return (workflow, history)."""
    rng = seed_everything(cfg.seed)
    run_dir = get_run_dir()

    # 1. Load the dataset generated by the simulate stage.
    data = io.load_dataset(os.path.join(cfg.data.data_dir, cfg.data.dataset_name))

    # 2. Deterministic preprocessing: fit on train split, transform train (+ val), persist state.
    pipeline = build_pipeline(cfg.preprocessing)
    train_data, val_data = pipeline.fit_transform(data, rng)
    pipeline.save(os.path.join(run_dir, PREPROCESSING_STATE))
    log.info(
        "Preprocessing done: %d train / %d val rows",
        io.n_rows(train_data), io.n_rows(val_data or {}),
    )

    # Keep only the keys the adapter consumes (simulator datasets carry extra arrays).
    train_data = select_adapter_keys(train_data, cfg)
    val_data = select_adapter_keys(val_data, cfg) if val_data is not None else None

    # 3. Build the workflow. Passing run_dir turns on best-val-loss checkpointing, restored below.
    workflow = build_workflow(cfg, run_dir=run_dir)

    # 4. Per-batch augmentations, with their own generator seeded from cfg.seed so their randomness
    #    is reproducible yet independent of the draws preprocessing already consumed from `rng`.
    augmentations = build_augmentations(
        cfg.augmentation, np.random.default_rng(cfg.seed), context={"pipeline": pipeline}
    )

    # Augmentations can change the observation layout (masks, extra features), so validation data
    # must pass through the same chain — once, with a fixed draw.
    if augmentations and val_data is not None:
        for aug in augmentations:
            val_data = aug(val_data)
        val_data = {k: np.asarray(v) for k, v in val_data.items()}

    # 5. Offline training. TerminateOnNaN stops a diverged run immediately; combined with the
    #    best-weights checkpoint, a late divergence costs no compute and no converged model.
    import keras

    def _fit(batch_size: int):
        return workflow.fit_offline(
            train_data,
            validation_data=val_data,
            epochs=int(cfg.training.n_epochs),
            batch_size=int(batch_size),
            augmentations=augmentations or None,
            verbose=int(cfg.training.verbose),
            callbacks=[keras.callbacks.TerminateOnNaN()],
        )

    # If the configured batch size does not fit on the card, halve it and retry (down to 16).
    history = run_with_oom_backoff(_fit, int(cfg.training.batch_size), logger=log)

    # 6. Persist the best weights seen, the model, and the loss history/curve.
    artifacts.restore_best_weights(workflow, run_dir)
    artifacts.save_approximator(workflow, run_dir)
    artifacts.save_history(history, run_dir)

    log.info("Training complete. Artifacts in %s", run_dir)
    return workflow, history


cli = make_cli(run_training)


if __name__ == "__main__":
    cli()
