"""Stage 2: training.

Load dataset -> preprocessing pipeline (fit on train, save fitted state for inference) -> build
workflow -> ``fit_offline`` with per-batch augmentations -> save approximator + loss curve.
Generalizes ``main_train_new_rotationcurve_agama.py``.
"""

from __future__ import annotations

import os

import numpy as np

from hydrabflow.augmentation.registry import build_augmentations
from hydrabflow.pipeline import io
from hydrabflow.pipeline._app import make_cli
from hydrabflow.pipeline.adapter import select_adapter_keys
from hydrabflow.pipeline.checkpoint import save_approximator
from hydrabflow.pipeline.workflow import build_workflow
from hydrabflow.preprocessing.registry import build_pipeline
from hydrabflow.utils.logging import get_logger
from hydrabflow.utils.paths import PREPROCESSING_STATE, get_run_dir
from hydrabflow.utils.seed import seed_everything

log = get_logger(__name__)


def run_training(cfg):
    """Train the approximator and return (workflow, history)."""
    rng = seed_everything(cfg.seed)
    run_dir = get_run_dir()

    # 1. Load the dataset generated by the simulate stage.
    dataset_path = os.path.join(cfg.data.data_dir, cfg.data.dataset_name)
    data = io.load_dataset(dataset_path)

    # 2. Deterministic preprocessing: fit on train split, transform train (+ val), persist state.
    pipeline = build_pipeline(cfg.preprocessing)
    train_data, val_data = pipeline.fit_transform(data, rng)
    pipeline.save(os.path.join(run_dir, PREPROCESSING_STATE))
    log.info("Preprocessing done: %d train / %d val rows",
             _n(train_data), _n(val_data) if val_data else 0)

    # Keep only the keys the adapter consumes (simulator datasets carry extra arrays).
    train_data = select_adapter_keys(train_data, cfg)
    val_data = select_adapter_keys(val_data, cfg) if val_data is not None else None

    # 3. Build the BayesFlow workflow (adapter + summary net + inference net). Passing run_dir
    #    turns on best-val-loss checkpointing (approximator_best.weights.h5), restored in step 6.
    workflow = build_workflow(cfg, run_dir=run_dir)

    # 4. Per-batch augmentations (stochastic, re-drawn each epoch). They get their own generator
    #    seeded from cfg.seed so augmentation randomness is reproducible yet independent of the
    #    draws preprocessing already consumed from `rng`. The fitted preprocessing pipeline is
    #    passed as context (per-stream standardization applies stats fitted on the train split).
    augmentations = build_augmentations(
        cfg.augmentation, np.random.default_rng(cfg.seed), context={"pipeline": pipeline}
    )

    # Augmentations can change the observation layout (masks, feature concatenations), so the
    # validation split must pass through the same chain — once, with a fixed draw.
    if augmentations and val_data is not None:
        for aug in augmentations:
            val_data = aug(val_data)
        val_data = {k: np.asarray(v) for k, v in val_data.items()}

    # 5. Offline training on the in-memory dataset. TerminateOnNaN stops immediately on a NaN loss
    #    (a diverged run has nothing left to learn); combined with best-weights checkpointing
    #    (step 3), a late divergence costs no compute and never overwrites a converged model.
    import keras

    history = workflow.fit_offline(
        train_data,
        validation_data=val_data,
        epochs=int(cfg.training.n_epochs),
        batch_size=int(cfg.training.batch_size),
        augmentations=augmentations if augmentations else None,
        verbose=int(cfg.training.verbose),
        callbacks=[keras.callbacks.TerminateOnNaN()],
    )

    # 6. Restore the best-val-loss weights saved during training (immune to a late NaN spike),
    #    then persist the approximator and a loss curve.
    _restore_best_weights(workflow, run_dir)
    save_approximator(workflow, run_dir)
    _save_loss_plot(history, run_dir)

    # 7. Save the raw training history and a convergence report (NaN / overfitting /
    #    under-training). Good training loss does not imply good inference, but a diverged or
    #    overfit run is worth flagging before the (chained) evaluation stage runs.
    _save_history_and_convergence(history, run_dir)

    log.info("Training complete. Artifacts in %s", run_dir)
    return workflow, history


def _restore_best_weights(workflow, run_dir: str) -> None:
    """Load the best-val-loss weights BayesFlow checkpointed during training back into the
    approximator, so the persisted model is the best one seen — not the last epoch (which may be
    worse, or NaN after a late divergence). Best-effort: a missing checkpoint (e.g. checkpointing
    disabled, or training never improved) leaves the in-memory weights untouched."""
    from hydrabflow.pipeline.workflow import BEST_WEIGHTS_NAME

    ckpt = os.path.join(run_dir, BEST_WEIGHTS_NAME + ".weights.h5")
    if not os.path.exists(ckpt):
        log.info("No best-weights checkpoint at %s; keeping final-epoch weights.", ckpt)
        return
    try:
        workflow.approximator.load_weights(ckpt)
        log.info("Restored best-val-loss weights from %s", ckpt)
    except Exception as exc:  # never fail a run over checkpoint restore
        log.warning("Could not restore best weights from %s: %s", ckpt, exc)


def _save_history_and_convergence(history, run_dir: str) -> None:
    """Persist ``history.json`` + ``convergence.json``; best-effort, never fails a run."""
    try:
        import json

        from hydrabflow.utils.paths import CONVERGENCE_JSON, HISTORY_JSON
        from hydrabflow.utils.reporting import inspect_history

        hist = getattr(history, "history", None) or {}
        with open(os.path.join(run_dir, HISTORY_JSON), "w") as f:
            json.dump({k: [float(x) for x in v] for k, v in hist.items()}, f, indent=2)

        report = inspect_history(hist)
        with open(os.path.join(run_dir, CONVERGENCE_JSON), "w") as f:
            json.dump(report, f, indent=2)

        if report["overall"]["ok"]:
            log.info("Training convergence: OK (no NaN / overfitting / under-training).")
        else:
            for issue in report["overall"]["issues"]:
                log.warning("Convergence check: %s", issue)
    except Exception as exc:  # inspection must never fail a training run
        log.warning("Could not save history/convergence report: %s", exc)


def _save_loss_plot(history, run_dir: str) -> None:
    try:
        import matplotlib

        matplotlib.use("Agg")
        import bayesflow as bf

        from hydrabflow.utils.paths import LOSS_PLOT

        fig = bf.diagnostics.plots.loss(history)
        fig.savefig(os.path.join(run_dir, LOSS_PLOT), bbox_inches="tight")
    except Exception as exc:  # plotting must never fail a training run
        log.warning("Could not save loss plot: %s", exc)


def _n(data) -> int:
    return len(next(iter(data.values()))) if data else 0


cli = make_cli(run_training)


if __name__ == "__main__":
    cli()
